#!/bin/bash

{
    rm ./compiler
    rm ./compiler.asm
    rm ./compiler.o
    rm ./test.oxy.ll
    rm ./a.out
} 2> /dev/null

oxy -o compiler ./src/main.oxy
./compiler "$1.oxy"
echo ''
clang "$1.oxy.ll" -o "$1" || exit 1
./$1